# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-11 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('town_or_city', models.CharField(max_length=40)),
                ('street_address1', models.CharField(max_length=40)),
                ('street_address2', models.CharField(max_length=40)),
                ('county', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('service_required', models.CharField(choices=[('logo_design', 'Logo Design'), ('full_brand_design', 'Full Brand Design'), ('business_card', 'Business Card'), ('brochure', 'Brochure'), ('leaflet', 'Leaflet'), ('full_print_design', 'Full Print Suite')], max_length=100)),
            ],
        ),
    ]
